# Generated by Django 6.0.3 on 2026-03-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_voicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicelog',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_logs/%Y/%m/'),
        ),
    ]
