from django.urls import path

from .views import (
    AlertDetailAPIView,
    AlertListAPIView,
    CircleDetailAPIView,
    CircleListCreateAPIView,
    CircleMemberDeleteAPIView,
    CircleMemberInviteAPIView,
    CircleMemberListAPIView,
    CircleNotificationSendAPIView,
    DashboardAPIView,
    FeedEntryListCreateAPIView,
    HealthAPIView,
    InsightsAPIView,
    LiveSyncAPIView,
    NotificationMarkReadAPIView,
    TaskActionAPIView,
    TaskDetailAPIView,
    TaskListCreateAPIView,
    VoiceLogListCreateAPIView,
    VoiceLogRetryAPIView,
    UserNotificationsAPIView,
    UserProfileAPIView,
    alerts_page,
    dashboard_demo,
    landing_page,
    landing_login,
    logs_page,
    members_management_page,
    notifications_page,
    profile_page,
    tasks_page,
)
from .views import AvailableMembersAPIView, MemberAvailabilityAPIView, MemberAvailabilityDeleteAPIView

urlpatterns = [
    path('', landing_page, name='landing-page'),
    path('login/', landing_login, name='landing-login'),
    path('dashboard/', dashboard_demo, name='dashboard-demo'),
    path('tasks/', tasks_page, name='tasks-page'),
    path('logs/', logs_page, name='logs-page'),
    path('alerts/', alerts_page, name='alerts-page'),
    path('api/health/', HealthAPIView.as_view(), name='api-health'),
    path('api/live-sync/', LiveSyncAPIView.as_view(), name='api-live-sync'),
    path('api/dashboard/', DashboardAPIView.as_view(), name='api-dashboard'),
    path('api/feed/', FeedEntryListCreateAPIView.as_view(), name='api-feed-list-create'),
    path('api/insights/', InsightsAPIView.as_view(), name='api-insights'),
    path('api/tasks/', TaskListCreateAPIView.as_view(), name='api-tasks-list-create'),
    path('api/tasks/<int:task_id>/', TaskDetailAPIView.as_view(), name='api-tasks-detail'),
    path('api/tasks/<int:task_id>/<str:action>/', TaskActionAPIView.as_view(), name='api-tasks-action'),
    path('api/voice-logs/', VoiceLogListCreateAPIView.as_view(), name='api-voice-logs-list-create'),
    path('api/voice-logs/<int:log_id>/retry/', VoiceLogRetryAPIView.as_view(), name='api-voice-logs-retry'),
    path('api/alerts/', AlertListAPIView.as_view(), name='api-alerts-list'),
    path('api/alerts/<int:alert_id>/', AlertDetailAPIView.as_view(), name='api-alerts-detail'),
    path('profile/', profile_page, name='profile-page'),
    path('notifications/', notifications_page, name='notifications-page'),
    path('circles/<int:circle_id>/members/', members_management_page, name='members-management'),
    path('api/profile/', UserProfileAPIView.as_view(), name='api-user-profile'),
    path('api/notifications/', UserNotificationsAPIView.as_view(), name='api-user-notifications'),
    path('api/notifications/<int:notification_id>/read/', NotificationMarkReadAPIView.as_view(), name='api-notification-read'),
    path('api/circles/', CircleListCreateAPIView.as_view(), name='api-circles-list-create'),
    path('api/circles/<int:circle_id>/', CircleDetailAPIView.as_view(), name='api-circles-detail'),
    # 'available/' must come before '<int:user_id>/' to avoid integer-capture conflict
    path('api/circles/<int:circle_id>/members/available/', AvailableMembersAPIView.as_view(), name='api-members-available'),
    path('api/circles/<int:circle_id>/members/', CircleMemberListAPIView.as_view(), name='api-circles-members-list'),
    path('api/circles/<int:circle_id>/members/invite/', CircleMemberInviteAPIView.as_view(), name='api-circles-members-invite'),
    path('api/circles/<int:circle_id>/members/<int:user_id>/', CircleMemberDeleteAPIView.as_view(), name='api-circles-members-delete'),
    path('api/circles/<int:circle_id>/members/<int:user_id>/availability/', MemberAvailabilityAPIView.as_view(), name='api-member-availability'),
    path('api/circles/<int:circle_id>/members/<int:user_id>/availability/<int:avail_id>/', MemberAvailabilityDeleteAPIView.as_view(), name='api-member-availability-delete'),
    path('api/circles/<int:circle_id>/notifications/', CircleNotificationSendAPIView.as_view(), name='api-circles-notifications'),
]
